version: '2'
services:
  common-db:
    image: postgres
    restart: always
    container_name: postgresdb
    environment:
      - POSTGRES_DB=banking_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bankingapp123
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d/
    ports:
      - 5433:5432
  auth-service:
    build:
      dockerfile: ../auth-service/Dockerfile
      context: ../auth-service
    ports:
      - "8081:8081"
  customer-service:
    build:
      dockerfile: ../customer-service/Dockerfile
      context: ../customer-service
    ports:
      - "8082:8082"
  payment-service:
    build:
      dockerfile: ../payment-service/Dockerfile
      context: ../payment-service
    ports:
      - "8083:8083"